
version: '2.1'

orbs:
  python: circleci/python@2.1.1

workflows:
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

jobs:
  build:
    docker:
      - image: cimg/python:3.10-browsers
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install library dependencies
          command: |
            # sudo apt install libjpeg-dev zlib1g-dev
            # sudo apt-get install freeglut3-dev
            pip install --upgrade pip
            python3 --version
            pip install html-testRunner~=1.2.1
            pip install pyglet==2.0.dev23
            pip install jsonpickle~=2.0.0
            pip install arcade~=2.6.7
            pip install Shapely~=1.8.0
      - run:
            name: run tests
            command: | 
              scripts/runtests.sh
