
from enum import Enum


class CommandType(Enum):
    Abandon   = 'Abandon'
    Chart     = 'Chart'
    Capture   = 'Capture'
    Call      = 'Call'      # (for help)
    Cloak     = 'Cloak'
    Computer  = 'Computer'
    Crystals  = 'Crystals'
    Damages   = 'Damages'
    DeathRay  = 'DeathRay'
    Destruct  = 'Destruct'
    Dock      = 'Dock'
    Freeze    = 'Freeze'        # Changed to save and load
    Impulse   = 'Impulse'
    Mine      = 'Mine'
    Move      = 'Move'
    Orbit     = 'Orbit'
    Phasers   = 'Phasers'
    Photons   = 'Photons'
    Planets   = 'Planets'
    Probe     = 'Probe'
    Report    = 'Report'
    Request   = 'Request'
    Rest      = 'Rest'
    Quit      = 'Quit'
    Score     = 'Score'
    Sensors   = 'Sensors'
    Shields   = 'Shields'
    Shuttle   = 'Shuttle'
    Status    = 'Status'
    Warp      = 'Warp'
    Help      = 'Help'
    Save      = 'Save'
    Load      = 'Load'
    Transport      = 'Transport'
    ShortScan      = 'ShortRangeScan'
    LongRangeScan  = 'LongRangeScan'
    EmergencyExit  = 'EmergencyExit'
    Event          = 'Event'
    NoCommand      = 'NoCommand'
