

WINDOW_BORDER_HEIGHT: int = 40
CONSOLE_HEIGHT:       int = 230

SCREEN_WIDTH:     int = 800
SCREEN_HEIGHT:    int = 600 + CONSOLE_HEIGHT

QUADRANT_GRID_WIDTH:  int = 640
QUADRANT_GRID_HEIGHT: int = 640

QUADRANT_PIXEL_HEIGHT: int = 64
QUADRANT_PIXEL_WIDTH:  int = 64

QUADRANT_Y_ADJUSTMENT: int = SCREEN_HEIGHT - QUADRANT_GRID_HEIGHT   # Adjustment from bottom

QUADRANT_ROWS:    int = 10
QUADRANT_COLUMNS: int = 10
QUADRANT_MARGIN:  int = 1

GALAXY_ROWS:   int = 10
GALAXY_COLUMNS: int = 10

STANDARD_SPRITE_WIDTH:  int = 32
STANDARD_SPRITE_HEIGHT: int = 32

STANDARD_X_ADJUSTMENT = (STANDARD_SPRITE_WIDTH / 2)
STANDARD_Y_ADJUSTMENT = (STANDARD_SPRITE_WIDTH / 2)
