
from collections import namedtuple

from unittest import TestSuite
from unittest import main as unitTestMain

from codeallybasic.UnitTestBase import UnitTestBase


from pytrek.gui.Common import PyTrekColor

TestRGBA = namedtuple('TestRGBA', ['r', 'g', 'b', 'alpha'])

TEST_RGBA_VALUE: TestRGBA = TestRGBA(r=20, g=40, b=75, alpha=160)
TEST_RGB_STR:    str      = f'{TEST_RGBA_VALUE.r},{TEST_RGBA_VALUE.g},{TEST_RGBA_VALUE.b},{TEST_RGBA_VALUE.alpha}'


class TestPyTrekColor(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 28 May 2026
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testToString(self):
        pyTrekColor:      PyTrekColor = PyTrekColor(r=TEST_RGBA_VALUE.r, g=TEST_RGBA_VALUE.g, b=TEST_RGBA_VALUE.b, alpha=TEST_RGBA_VALUE.alpha)
        expectedStrValue: str         = str(pyTrekColor)

        self.assertEqual(f'{TEST_RGBA_VALUE.r},{TEST_RGBA_VALUE.g},{TEST_RGBA_VALUE.b},{TEST_RGBA_VALUE.alpha}', expectedStrValue, 'String conversion not working')

    def testDeSerialize(self):
        expectedPyTrekColor: PyTrekColor = PyTrekColor(r=TEST_RGBA_VALUE.r, g=TEST_RGBA_VALUE.g, b=TEST_RGBA_VALUE.b, alpha=TEST_RGBA_VALUE.alpha)
        actualPyTrekColor:   PyTrekColor = PyTrekColor.deSerialize(TEST_RGB_STR)

        self.assertEqual(expectedPyTrekColor, actualPyTrekColor, 'Deserialization not working')

def suite() -> TestSuite:
    import unittest


    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestPyTrekColor))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
